#!/bin/sh -e

cmake -B objects -G Ninja && ninja -C objects install/strip

if /usr/bin/pidof X > /dev/null 2>&1; then
    { [ ! -f "../lua/neoclip_wl.so" ] || [ ! -f "../lua/neoclip_x11.so" ]; } || rm -rf ./objects
else
    [ ! -f "../lua/neoclip_wl.so" ] || rm -rf ./objects
fi
